# Generated by Django 6.0.1 on 2026-01-19 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speaker_designation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker_organization',
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.event')),
            ],
        ),
    ]
