# Generated by Django 6.0.1 on 2026-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_speaker_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.speaker'),
        ),
    ]
