# Generated by Django 6.0.1 on 2026-01-20 06:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_speaker_event_event_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
