# Generated by Django 6.0.1 on 2026-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_speaker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventday',
            name='details',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
