# Generated by Django 6.0.1 on 2026-01-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventday_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventday',
            name='details',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
