# Generated by Django 6.0.1 on 2026-01-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventday_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
